# Generated by Django 4.1.2 on 2023-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cablesize_conductors_jacketrating_cable_conductors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='conductors',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='rating',
        ),
        migrations.AlterField(
            model_name='cable',
            name='size',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CableSize',
        ),
        migrations.DeleteModel(
            name='Conductors',
        ),
        migrations.DeleteModel(
            name='JacketRating',
        ),
    ]
