# Generated by Django 4.1.2 on 2023-07-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_cable_conductors_remove_cable_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conductors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductors', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JacketRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cable',
            name='conductors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.conductors'),
        ),
        migrations.AddField(
            model_name='cable',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.jacketrating'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cablesize'),
        ),
    ]
