# Generated by Django 4.1.2 on 2023-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cablesize_conductors_jacketrating_cable_conductors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
