# Generated by Django 4.1.2 on 2023-07-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_innerdimension_outerdimension_conduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='conductors',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='rating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CableSize',
        ),
        migrations.DeleteModel(
            name='Conductors',
        ),
        migrations.DeleteModel(
            name='JacketRating',
        ),
    ]
