# Generated by Django 4.1.2 on 2023-07-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_cable_conductors_alter_cable_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conduit',
            old_name='name',
            new_name='conduittag',
        ),
        migrations.CreateModel(
            name='CableRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabletag', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('cablerun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.cable')),
            ],
        ),
    ]
