# Generated by Django 4.1.2 on 2023-07-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_name_conduit_conduittag_cablerun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conduit',
            old_name='conduittag',
            new_name='name',
        ),
    ]
