# Generated by Django 4.1.2 on 2023-07-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_conduittag_conduit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduit',
            name='InnerDimension',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='OuterDimension',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
