# Generated by Django 4.1.2 on 2023-07-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_conduit_innerdimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConduitRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduitag', models.CharField(max_length=200)),
                ('conduitrun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.conduit')),
            ],
        ),
    ]
