# Generated by Django 4.1.2 on 2023-07-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_conduitrun_cablerun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InnerDimension',
        ),
        migrations.DeleteModel(
            name='OuterDimension',
        ),
        migrations.RenameField(
            model_name='conduitrun',
            old_name='conduitag',
            new_name='conduittag',
        ),
    ]
