# Generated by Django 4.1.2 on 2023-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_innerdimension_delete_outerdimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablerun',
            name='cablerun',
        ),
        migrations.AddField(
            model_name='cablerun',
            name='cablerun',
            field=models.ManyToManyField(to='users.cable'),
        ),
    ]
