# Generated by Django 4.1.2 on 2023-07-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_conduitrun_conduitrun_conduitrun_conduitrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablerun',
            name='cablerun',
        ),
    ]
