# Generated by Django 4.1.2 on 2023-07-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_cablerun_cablerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablerun',
            name='cablerun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.cable'),
            preserve_default=False,
        ),
    ]
