# Generated by Django 4.1.2 on 2023-07-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_cablerun_cablerun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cablerun',
            old_name='cablerun',
            new_name='cable',
        ),
        migrations.RenameField(
            model_name='conduitrun',
            old_name='cablerun',
            new_name='cable',
        ),
    ]
