# Generated by Django 4.1.2 on 2024-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CableApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduit',
            name='Area',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
