# Generated by Django 4.1.2 on 2024-01-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CableApp', '0003_alter_conduit_innerdimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduit',
            name='Area',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='InnerDimension',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='OuterDimension',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
