# Generated by Django 4.1.2 on 2024-01-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CableApp', '0004_alter_conduit_area_alter_conduit_innerdimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='OuterDim',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
