# Generated by Django 5.0.1 on 2024-01-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CableApp', '0005_cable_outerdim'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduitrun',
            name='fill',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
