# Generated by Django 5.0.1 on 2024-01-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CableApp', '0006_conduitrun_fill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='OuterDim',
            new_name='OuterDimension',
        ),
    ]
